//
// e2e.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once

void e2e(
	const double xrels[],
	const double yrels[],
	const double zrels[],
	const double srcexps[],
	double dstexp[]);
