//
// kernels.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_KERNELS_H
#define ISPC_KERNELS_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void e2e(const double * x0s, const double * y0s, const double * masses, const double *  * vrxps, const double *  * vixps, double * rdstxp, double * idstxp);
    extern double e2p(const double * xrel, const double * yrel, const int32_t nexps, const double * Q, const double *  * re, const double *  * ie);
    extern void p2e(const double * xsources, const double * ysources, const double * qsources, const int32_t nsources, const double xcom, const double ycom, double * rexpansions, double * iexpansions);
    extern double p2p(const double * xsrc, const double * ysrc, const double * qsrc, const int32_t nsrc, const double xt, const double yt);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_KERNELS_H
