//
// treekernels.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_TREEKERNELS_H
#define ISPC_TREEKERNELS_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void minmax(const int32_t N, const double * x, const double * y, const double * z, double &xmin, double &xmax, double &ymin, double &ymax, double &zmin, double &zmax);
    extern void morton(const int32_t N, const double * x, const double * y, const double * z, const double xmin, const double ymin, const double zmin, const double ext, int32_t * index, const int32_t ntasks);
    extern void node_setup(const double * xs, const double * ys, const double * zs, const double * qs, const int32_t n, double &Q, double &xcom, double &ycom, double &zcom, double &radius, double &weight);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_TREEKERNELS_H
